name: 'sc_entrepreneurship_analytics'
version: '1.0.0'
config-version: 2

profile: 'sc_duckdb_profile'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"
models:
  sc_entrepreneurship_analytics:
    staging:
      +materialized: view
      +schema: staging    
    marts:
      +materialized: table
      +schema: main
vars:
  start_date: '2021-01-01'
  is_mock_data: true